fix issue that cannot handle GITHUB__APP__PRIVATE_KEY variable properly
redhat-appstudio/rhtap-installer pull request #134
Opened 2024-04-15 07:34 UTC by xinredhat

rh-pre-commit.version: 2.1.0
rh-pre-commit.check-secrets: ENABLED

2024-04-15 12:13 UTC, Roming22 requested changes

2024-04-15 13:02 UTC, Roming22 commented
/cherry-pick release-1.0

2024-04-15 13:03 UTC, merged

2024-04-15 18:48 UTC, maysunfaisal commented
@xinredhat @Roming22 interesting that with this PR I can no longer do

```
export GITHUB__APP__PRIVATE_KEY=`cat /Users/maysun/private-key.pem`
```

I was able to export it like this prior to this PR. 🤔

2024-04-23 18:40 UTC, Roming22 commented
@maysunfaisal I can't reproduce the issue.

```
> export KEY=`cat ~/Downloads/roming22-rhtap-connector.2024-04-23.private-key.pem`

> echo "$KEY" | tr -d '\n' | grep --extended-regexp --count "^-----BEGIN RSA PRIVATE KEY-----.*-----END RSA PRIVATE KEY-----$"
1
```

Can you check that in your case the last command returns `0`? If it does, contact me on Slack and we will troubleshoot together.